IF(NOT BIBLESYNC_SOVERSION AND BUILD_SHARED_LIBS)
    SET(BIBLESYNC_SOVERSION ${BIBLESYNC_VERSION})
ELSE(NOT BIBLESYNC_SOVERSION AND BUILD_SHARED_LIBS)
    SET(BIBLESYNC_SOVERSION ${BIBLESYNC_SOVERSION})
ENDIF(NOT BIBLESYNC_SOVERSION AND BUILD_SHARED_LIBS)

IF(BUILD_SHARED_LIBS)
	SET_TARGET_PROPERTIES(biblesync
        PROPERTIES SOVERSION ${BIBLESYNC_SOVERSION})
    MESSAGE(STATUS "Setting SOVERSION to ${BIBLESYNC_SOVERSION}")
ENDIF(BUILD_SHARED_LIBS)
